GameStore_MVC/Controllers/CustomerController.cs
using GameStore_MVC.Data;
using GameStore_MVC.Data.Entities;
using GameStore_MVC.Models.GameStoreViewModels.CustomerVM;
using Microsoft.AspNetCore.Mvc;

namespace GameStore_MVC.Controllers
{
	public class CustomerController : Controller
	{
		private readonly ApplicationDbContext _context;

		public CustomerController(ApplicationDbContext context)
		{
			_context = context;
		}

		public IActionResult Index()
		{
			var customers = _context.Customers.Select(customer => new CustomerIndex
			{
				Id = customer.Id,
				Name = customer.Name,
				Email = customer.Email,
			});
			return View(customers);
		}

		// GET: Customer/Create
		public IActionResult Create()
		{
			return View();
		}

		// POST: Customer/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Create(CustomerCreate model)
		{
			if (!ModelState.IsValid)
			{
				TempData["ErrorMsg"] = "Model State is invalid";
				return View(model);
			}
			_context.Customers.Add(new Customer
			{
				Name = model.Name,
				Email = model.Email
			});
			if (_context.SaveChanges() == 1)
			{
				return Redirect("/Customer");
			}
			TempData["ErrorMsg"] = "Unable to save to the database.Please try again later.";
			return View(model);
		}
		// GET: Customer/Details
		public IActionResult Details(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}
			var customer = _context.Customers.Find(id);
			if (customer == null)
			{
				return NotFound();
			}
			var model = new CustomerDetail
			{
				Id = customer.Id,
				Name = customer.Name,
				Email = customer.Email
			};
			return View(model);
		}

		// GET: Customer/Edit
		[HttpGet]
		public IActionResult Edit(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}
			var customer = _context.Customers.Find(id);
			if (customer == null)
			{
				return NotFound();
			}
			var model = new CustomerEdit
			{
				Id = customer.Id,
				Name = customer.Name,
				Email = customer.Email
			};
			return View(model);
		}

		// POST: Customer/Edit
		[HttpPost]
		public IActionResult Edit(int id, CustomerEdit model)
		{
			var customer = _context.Customers.Find(id);
			if (customer == null)
			{
				return NotFound();
			}
			customer.Name = model.Name;
			customer.Email = model.Email;

			if (_context.SaveChanges() == 1)
			{
				return Redirect("/customer");
			}

			ViewData["ErrorMsg"] = "Unable to save to the database. Please try again.";
			return View(model);
		}

		// GET: Customer/Delete
		[HttpGet]
		public IActionResult Delete(int id)
		{
			if (id == null)
			{
				return NotFound();
			}
			var customer = _context.Customers.Find(id);
			if (customer == null)
			{
				return NotFound();
			}
			var model = new CustomerDetail
			{
				Id = customer.Id,
				Name = customer.Name,
				Email = customer.Email
			};
			return View(model);
		}

		// POST: Customer/Delete
		[HttpPost]
		public IActionResult Delete(int? id, CustomerDetail model)
		{
			var customer = _context.Customers.Find(id);
			if (customer == null)
			{
				return NotFound();
			}
			_context.Customers.Remove(customer);
			_context.SaveChanges();
			return Redirect("/Customer");
		}
	}
}

GameStore_MVC/Controllers/GameController.cs
using GameStore_MVC.Models.GameStoreViewModels.GameVM;
using GameStore_MVC.Services.Contracts;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace GameStore_MVC.Controllers
{
	public class GameController : Controller
	{
		private IGameService _service;
		private IGameDevService _devService;

		public GameController(IGameService service, IGameDevService devService)
		{
			_service = service;
			_devService = devService;
		}

		// GET: Game
		public async Task<IActionResult> Index()
		{
			return View(await _service.GetGames());
		}

		// GET: Game/Create
		[HttpGet]
		[Route("Create")]
		public async Task<IActionResult> Create()
		{
			var gameDevVM = new GameCreate
			{
				GameOptions = _devService.GetGameDevs().Result.ToList().Select(g => new SelectListItem
				{
					Text = g.Developer,
					Value = g.Id.ToString(),
				})
			};

			return View(gameDevVM);
		}

		// POST: Game/Create
		[HttpPost]
		[Route("Create")]
		public async Task<IActionResult> Create(GameCreate model)
		{
			if (ModelState.IsValid)
			{
				if (await _service.AddGame(model))
				{
					return RedirectToAction(nameof(Index));
				}
			}

			var GameOptions = _devService.GetGameDevs().Result.ToList().Select(g => new SelectListItem
			{
				Text = g.Developer,
				Value = g.Id.ToString(),
			});
			model.GameOptions = GameOptions;


			return View();
		}

		// GET: Game/Details
		[HttpGet]
		public async Task<IActionResult> Details(int id)
		{
			return View(await _service.GetGame(id));
		}

		// GET: Game/Edit
		[HttpGet]
		[Route("Edit/{id}")]
		public async Task<IActionResult> Edit(int id)
		{
			var game = await _service.GetGame(id);
			var gameEdit = new GameEdit
			{
				Id = game.Id,
				Title = game.Title,
				Description = game.Description,
				Price = game.Price,
				QuantityInStock = game.QuantityInStock,
				ImageURL = game.ImageURL,
				AgeRating = game.AgeRating,
				Platform = game.Platform
			};

			var gameVM = new GameEdit
			{
				GameOptions = _devService.GetGameDevs().Result.ToList().Select(g => new SelectListItem
				{
					Text = g.Developer,
					Value = g.Id.ToString(),
				})
			};
			gameEdit.GameOptions = gameVM.GameOptions;



			return View(gameEdit);
		}

		// POST: Game/Edit
		[HttpPost]
		[Route("Edit/{id}")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, GameEdit model)
		{
			if (id != model.Id) return BadRequest("Invalid Id");
			if (!ModelState.IsValid) return BadRequest(ModelState);
			if (await _service.UpdateGame(id, model))
				return RedirectToAction(nameof(Index));
			else
			{
				var GameOptions = _devService.GetGameDevs().Result.ToList().Select(g => new SelectListItem
				{
					Text = g.Developer,
					Value = g.Id.ToString(),
				});
				model.GameOptions = GameOptions;
			}
			return View(model);
		}


		// GET: Game/Delete
		[HttpGet]
		[Route("Delete/{id}")]
		public async Task<IActionResult> Delete(int? id)
		{
			var game = await _service.GetGame(id.Value);
			return View(game);
		}

		// POST: Game/Delete
		[HttpPost]
		[Route("Delete/{id}")]
		public async Task<IActionResult> Delete(int id)
		{
			var isSuccessful = await _service.DeleteGame(id);
			if (isSuccessful)
				return RedirectToAction(nameof(Index));
			else
				return UnprocessableEntity();
		}
	}
}

GameStore_MVC/Controllers/GameDevController.cs
using GameStore_MVC.Models.GameStoreViewModels.GameDevVM;
using GameStore_MVC.Services.Contracts;
using Microsoft.AspNetCore.Mvc;

namespace GameStore_MVC.Controllers
{
	public class GameDevController : Controller
	{
		private IGameDevService _service;
		private IGameService _gameService;

		public GameDevController(IGameDevService service, IGameService gameService)
		{
			_service = service;
			_gameService = gameService;
		}
		[HttpGet]
		public async Task<IActionResult> Index()
		{
			return View(await _service.GetGameDevs());
		}

		// GET: GameDev/Create
		[HttpGet]
		public async Task<IActionResult> Create()
		{
			var gameDevVM = new GameDevCreate();

			return View(gameDevVM);
		}

		// POST: GameDev/Create
		[HttpPost]
		[ActionName("Create")]
		public async Task<IActionResult> CreateGameDev(GameDevCreate model)
		{
			if (ModelState.IsValid)
			{
				if (await _service.AddGameDev(model))
				{
					return RedirectToAction(nameof(Index));
				}
			}

			return View(model);
		}

		// GET: GameDev/Details
		[HttpGet]
		public async Task<IActionResult> Details(int id)
		{
			return View(await _service.GetGameDev(id));
		}

		// GET: GameDev/Edit
		[HttpGet]
		public async Task<IActionResult> Edit(int id)
		{
			var gameDev = await _service.GetGameDev(id);
			var gameDevEdit = new GameDevEdit
			{
				Id = gameDev.Id,
				Developer = gameDev.Developer,
				City = gameDev.City,
				Country = gameDev.Country,
				Est = gameDev.Est,

			};

			return View(gameDevEdit);
		}

		// POST: GameDev/Edit
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, GameDevEdit model)
		{
			if (id != model.Id) return BadRequest("Invalid Id");
			if (!ModelState.IsValid) return BadRequest(ModelState);
			if (await _service.UpdateGameDev(id, model))
				return RedirectToAction(nameof(Index));
			else
			{
				return View(model);
			}
		}

		// GET: GameDev/Delete
		[HttpGet]
		public async Task<IActionResult> Delete(int? id)
		{
			var gameDev = await _service.GetGameDev(id.Value);
			return View(gameDev);
		}

		// POST: GameDev/Delete
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Delete(int id)
		{
			var isSuccessful = await _service.DeleteGameDev(id);
			if (isSuccessful)
				return RedirectToAction(nameof(Index));
			else
				return UnprocessableEntity();
		}
	}
}

GameStore_MVC/Controllers/OrderController.cs
using GameStore_MVC.Data;
using GameStore_MVC.Data.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace GameStore_MVC.Controllers
{
    public class OrderController : Controller
    {
        private readonly ApplicationDbContext _context;

		public OrderController(ApplicationDbContext context)
		{
			_context = context;
		}

		public async Task<IActionResult> Index()
        {
			var applicationDbContext = _context.Orders.Include(t => t.Customer).Include(t => t.Game);
			return View(await applicationDbContext.ToListAsync());
		}

		// GET: Order/Details
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var order = await _context.Orders
				.Include(t => t.Customer)
				.Include(t => t.Game)
				.FirstOrDefaultAsync(m => m.Id == id);
			if (order == null)
			{
				return NotFound();
			}

			return View(order);
		}

		// GET: Order/Create
		public IActionResult Create()
		{
			ViewData["CustomerId"] = new SelectList(_context.Customers, "Id", "Id");
			ViewData["GameId"] = new SelectList(_context.Games, "Id", "Id");
			return View();
		}

		// POST: Order/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("Id,GameId,CustomerId,Quantity,DateOfOrder")] Order order)
		{
			if (ModelState.IsValid)
			{
				_context.Add(order);
				await _context.SaveChangesAsync();
				return RedirectToAction(nameof(Index));
			}
			ViewData["CustomerId"] = new SelectList(_context.Customers, "Id", "Id", order.CustomerId);
			ViewData["GameId"] = new SelectList(_context.Games, "Id", "Id", order.GameId);
			return View(order);
		}

		// GET: Order/Edit
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null || _context.Orders == null)
			{
				return NotFound();
			}

			var order = await _context.Orders.FindAsync(id);
			if (order == null)
			{
				return NotFound();
			}
			ViewData["CustomerId"] = new SelectList(_context.Customers, "Id", "Id", order.CustomerId);
			ViewData["GameId"] = new SelectList(_context.Games, "Id", "Id", order.GameId);
			return View(order);
		}

		// POST: Order/Edit/
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, [Bind("Id,GameId,CustomerId,Quantity,DateOfOrder")] Order order)
		{
			if (id != order.Id)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				try
				{
					_context.Update(order);
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!TransactionExists(order.Id))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}
			ViewData["CustomerId"] = new SelectList(_context.Customers, "Id", "Id", order.CustomerId);
			ViewData["GameId"] = new SelectList(_context.Games, "Id", "Id", order.GameId);
			return View(order);
		}

		// GET: Order/Delete/5
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null || _context.Orders == null)
			{
				return NotFound();
			}

			var order = await _context.Orders
				.Include(t => t.Customer)
				.Include(t => t.Game)
				.FirstOrDefaultAsync(m => m.Id == id);
			if (order == null)
			{
				return NotFound();
			}

			return View(order);
		}

		// POST: Order/Delete
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			if (_context.Orders == null)
			{
				return Problem("Entity set 'ApplicationDbContext.Orders'  is null.");
			}
			var order = await _context.Orders.FindAsync(id);
			if (order != null)
			{
				_context.Orders.Remove(order);
			}

			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}

		private bool TransactionExists(int id)
		{
			return (_context.Orders?.Any(e => e.Id == id)).GetValueOrDefault();
		}
	}
}

GameStore_MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GameStore_MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/GameStore_MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Game" asp-action="Index">Game Store MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Game" asp-action="Index">Games</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="GameDev" asp-action="Index">Game Developers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Order" asp-action="Index">Orders</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Customer" asp-action="Index">Customer</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Options</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-area="" asp-controller="Game" asp-action="Create">Create a Game</a>
                                <a class="dropdown-item" asp-area="" asp-controller="GameDev" asp-action="Create">Create a Game Dev</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Order" asp-action="Create">Create a Order</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Customer" asp-action="Create">Create a Customer</a>


                            </div>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted">
        <div class="container">
            &copy; 2023 - Game Store MVC
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>